# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:22
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170120_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'', verbose_name={b'crop': False, b'size': (500, 500)}),
        ),
    ]
