# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:31
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170120_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=b''),
        ),
    ]
