# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170120_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_resized',
            field=models.BooleanField(default=False),
        ),
    ]
